name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: "Publish to npm"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Verify tag is on main
        run: git merge-base --is-ancestor ${{ github.sha }} origin/main
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/*"
      - run: corepack enable
      - run: yarn install
      - run: npm publish --provenance --access public
